### ISSUE TITLE
Enhancements to the content snap

### ISSUE THREAD

**Issue by soumyaDghosh** [snapcrafters/ffmpeg-2404-sdk#1]
The ffmpeg here can be built with these options too 

1. --enable-stripping
2. --toolchains=hardened

But, I need to dig deep about the consequences. @iomezk would like if you could give me some insights on this.

**Comment by iomezk** [comment]
Debian/Ubuntu .deb ffmpeg packages are built with
```
... --toolchain=hardened ... --disable-stripping ...
```
What `hardened` does https://github.com/FFmpeg/FFmpeg/blob/d799ad2/configure#L4484
`stripping` is enabled by default https://github.com/FFmpeg/FFmpeg/blob/d799ad2/configure#L3972

**Comment by soumyaDghosh** [comment]
> Debian/Ubuntu .deb ffmpeg packages are built with

I actually took the base from the old ffmpeg snap, and it's not mentioned there. So, I thought, these are all.

https://github.com/snapcrafters/ffmpeg/blob/master/snap/snapcraft.yaml#L170

Thanks for the input, but... I am still not sure whether to put it or not. As much I understood, it's not used by freedesktop themselves in their SDK.

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/elements/include/ffmpeg.yml
